# Generated by Django 5.1.1 on 2024-09-16 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('HexColor', models.CharField(blank=True, max_length=20, null=True)),
                ('Product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
