# Generated by Django 5.1.1 on 2024-09-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
