# Generated by Django 5.1.1 on 2024-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_slide_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikala_services',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
