# Generated by Django 5.1.1 on 2024-09-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_digikala_services_create_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='OfferPack',
        ),
    ]
