# Generated by Django 5.1.1 on 2024-09-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='Product',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
