# Generated by Django 5.1.1 on 2024-09-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_comment_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(to='main.brand'),
        ),
    ]
