# Generated by Django 5.1.1 on 2024-09-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(related_name='products', to='main.brand'),
        ),
    ]
