# Generated by Django 5.1.1 on 2024-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
